"""Verbatim micro-step of cl_lora/engine.py train_task at 4257d86 (lines 387-403), the
reference for the grouped engine step. Generated by Task 10 of
docs/superpowers/plans/2026-10-05-h200-throughput.md; do not edit by hand."""
import torch

from cl_lora import treelora as tree_mod

ORTH = ("olora", "gainlora_o")


def reference_engine_micro_step(a, model, mb, nmb, device, task_id, mgr, tree, gates, cur):
    mb = {k: v.to(device) for k, v in mb.items()}
    labels = nmb["label"].to(device)
    if gates is not None:
        gates.set_batch_gates(mb["input_ids"], mb["attention_mask"])
    logits = model(**mb, use_cache=False).logits
    loss = torch.nn.functional.cross_entropy(
        logits[:, :-1].reshape(-1, logits.size(-1)).float(), labels[:, 1:].reshape(-1))
    if mgr is not None and a.cl_method in ORTH:
        loss = loss + mgr.orth_loss(cur)
    if tree is not None:
        tree.step()
        sig = tree_mod.signature_from_model(model, cur)
        tree.insert_grad(sig)
        if task_id > 0:
            prev = tree.tree_search(task_id, device)
            loss = loss - tree.get_loss(sig, loss, task_id, prev)
    (loss / a.grad_accum).backward()
